### PR TITLE
WIP First attempt at helper to add IP address

### PR DESCRIPTION
**Pull request by michaeljcollinsuk**
- Adds new dependencies for the function
- Add helpers.py file with the new function

### CODE REVIEW

**Comment by symroe** [comment]
Few thoughts on this:

1. We will learn over time if this is best in this package or as it's own repo that we can package and publish to `PyPi` - let's keep it here for now.
2. With that in mind, let's make the sub-package here a little more distinct - maybe as a package _inside_ a `helpers` package (so at `helpers/update_ec2_sg/[files]` or something)
3. I think the description and sg name should be able to read from a config file at `~/.config/[command_name]/config` - I like the default description being the username though.
4. We should expose this command using the [console scripts entry point](https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-console-scripts-entry-point) in `setup.py`

**Comment by michaeljcollinsuk** [comment]
> 3. I think the description and sg name should be able to read from a config file at `~/.config/[command_name]/config` - I like the default description being the username though.

Just to check, so the idea here would be a user sets up the this file on their machine (as opposed to the file existing in the repo) which the function is then reads from? Any examples/suggested reading would be useful thanks ([is this the right direction?](https://docs.python.org/3/library/configparser.html))

**Comment by symroe** [comment]
Yes, that's what I'm thinking - a non-checked in file that can define the group name and description (with some defaults).

There are some standards around this, e.g here https://0x46.net/thoughts/2019/02/01/dotfile-madness/ (a write up of https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html). I think using https://docs.python.org/3/library/configparser.html would be ideal.

There is https://github.com/rec/cfgs, but I don't think it's worth using in our case - we don't have a cache or other features, just a config file.

**Comment by symroe** [comment]
We're mostly using `ec2-instance-connect` now, so I think this is safe to close

**Pull request closed without merging**
